config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "patients#home"

  resources :patients do
    collection do
      get :home
      get :start
      get :search
    end
    member do
      get :delete
      post :destory
    end
  end

  get 'inizio', to: 'patients#start', as: 'inizio'
  get 'home', to: 'patients#home', as: 'home'

  resources :examinations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :locations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :users do
    member do
      get :delete
      post :destroy
      post :change_location
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :examinations
  has_and_belongs_to_many :locations
  belongs_to :location, optional: true

  def fullname
    if fname.present? && lname.present?
      "#{fname}" ' ' "#{lname}"
    else
      "#{email}"
    end
  end

  def is_admin?
    if role == "admin"
      return true
    end
  end

  def is_medic?
    if role == "medic"
      return true
    end
  end

  def is_manager?
    if role == "manager"
      return true
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def delete
    @user = User.find(params[:id])
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  def change_location
    @location = Location.find(params[:location_id])
    current_user.location = @location
    current_user.save
    respond_to do |format|
      format.js
    end
  end

  private
  def user_params
    params.require(:user).permit(:fname,
                                 :lname,
                                 :location_id,
                                 location_ids:[]
                                )
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.input :fname, label: 'Nome' %>
  <%= f.input :lname, label: 'Cognome' %>

  <%= f.association :locations, label_method: :title %>

  <%= f.submit 'Salva', class: 'btn btn-primary' %>
<% end %>

app/views/users/change_location.js.erb
$('.current-location').html("<%= @location.title %>")

app/views/users/edit.html.erb
<div class="container my-5">
  <h1>Modifica dati utente</h1>
  <h5>Per: <%= @user.fullname %></h5>

  <div class="small-form mt-5">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container my-5">
  <h1>Operatori</h1>
  <p>Di seguito i nomi degli operatori e le sedi dove possono lavorare</p>
</div>
<div class="container mb-5">
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-3">
        <%= link_to user_path(user) do %>
          <div class="p-3 border">
            <h5><%= user.fullname %></h5>
            <ul>
              <% if user.locations.present? %>
                <% user.locations.each do |loc| %>
                  <li><%= loc.title %></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <div class="row pb-4 border-bottom">
    <div class="col-sm-8">
      <h1><%= @user.fullname %></h1>
    </div>
    <div class="col-sm-4">
      <%= link_to 'Modifica dati utente', edit_user_path(@user), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class="container my-4">
  <div class="row pb-3 border-bottom">
    <div class="col-sm-3">
      <h5>Sedi operative</h5>
      <ul class="list-group">
        <% @user.locations.each do |location| %>
          <%= link_to change_location_user_path(location_id: location.id), remote: true, method: :post do %><li class="text-center list-group-item"><%= location.title %></li><% end %>
        <% end %>
      </ul>
    </div>

    <div class="col-sm-9">

      <div class="fluid-container my-4 pb-4">
        <div class="row justify-content-center">
          <div class="col-sm-3 text-center align-self-center mb-2">
            <div class="p-3 border">
              <h3>Ruolo:</h3>
              <h2><%= @user.role == 'medic' ? 'Medico' : '' %></h2>
            </div>
          </div>

          <div class="col-sm-3 text-center align-self-center mb-2">
            <div class="p-3 border">
              <h3>Interventi:</h3>
              <h2><%= @user.examinations.count %></h2>
            </div>
          </div>

          <div class="col-sm-3 text-center align-self-center">
            <div class="p-3 border">
              <h3>Sedi attuale:</h3>
              <h2 class="current-location"><%= @user.location.present? ? @user.location.title : 'nd' %></h2>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>



<div class="container my-4">
  <h2 class="pb-2">Interventi</h2>
  <table class="table table-striped">
    <thead>
      <th>Data</th>
      <th>Paziente</th>
      <th>Esito</th>
      <th>Link</th>
    </thead>
    <tbody>
      <% @user.examinations.each do |exam| %>
        <tr>
          <td><%= l exam.exam_time, format: :long %></td>
          <td><%= exam.patient.fullname %></td>
          <td><%= exam.result %></td>
          <td><%= link_to examination_path(exam) do %><%= fa_icon 'arrow-right' %><% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>