config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "patients#home"

  resources :patients do
    collection do
      get :home
      get :start
      get :search
    end
    member do
      get :delete
      post :destory
    end
  end

  get 'inizio', to: 'patients#start', as: 'inizio'
  get 'home', to: 'patients#home', as: 'home'

  resources :examinations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :locations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :users do
    member do
      get :delete
      post :destroy
      post :change_location
    end
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :examinations

  def fullname
    "#{fname}" + ' ' + "#{lname}"
  end

  # search
  def self.search_fiscalcode(search)
    where("fiscalcode like ?", "#{search}")
  end
  def self.search_name(search)
    where("fname ILIKE ? OR lname ILIKE ? OR (fname || ' ' || lname) ILIKE ? OR (lname || ' ' || fname) ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  end

  def age
    ((Time.zone.now - birth_date.to_time) / 1.year.seconds).floor
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :search, :show, :edit, :create, :update, :delete, :destroy]
  require 'json'
  require 'open-uri'

  def start
  end

  def home
    if !user_signed_in?
      redirect_to start_patients_path
    end
  end

  def index
    @patients = Patient.order(lname: :asc)
    if params.has_key?(:q)
      @patients = Patient.search_name(params[:q])
    end
    if params.has_key?(:search)
      @patients = Patient.search_name(params[:search][:query]).order(lname: :asc)
    end
    authorize!

    respond_to do |format|
      format.html
      format.json
    end
  end

  def search
    if params.has_key?(:search)
      @patients = Patient.search_fiscalcode(params[:search][:query]).order(lname: :asc)
      respond_to do |format|
        format.js do
          if @patients.blank?
            @after_form = true
            render 'new'
          else
            render 'search'
          end
        end
      end
    end
    authorize!
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      flash[:notice] = "Paziente aggiunto correttamente"
      if params[:patient][:create_patient_and_exam]
        redirect_to new_examination_path(patient_id: @patient)
      else
        redirect_to patient_path(@patient)
      end
    end
  end

  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    @patient.update(patient_params)
    flash[:notice] = "Dati paziente aggiornati"
    redirect_to patient_path(@patient)
  end

  def delete
    @patient = Patient.find(params[:id])
  end

  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy
    redirect_to patients_path
  end

  private
  def patient_params
    params.require(:patient).permit(:fname,
                                    :lname,
                                    :fiscalcode,
                                    :address,
                                    :city,
                                    :province,
                                    :birth_date,
                                    :anamnesis,
                                    :eo,
                                    :notes
                                  )
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div class="fluid-container">
  <%= simple_form_for :patient, url: '../patients', authenticity_token: true, remote: true, method: :post do |f| %>
  <div class="form-row">
    <div class="col-sm-5"><%= f.input :fname, label: 'Nome' %></div>
    <div class="col-sm-5"><%= f.input :lname, label: 'Cognome' %></div>
    <div class="col-sm-2"><%= f.input :gender, collection: ['M', 'F'], label: 'Sesso', include_blank: false %></div>
  </div>
  <div class="form-row">
    <div class="col-sm-6"><%= f.input :fiscalcode, label: 'Codice fiscale' %></div>
    <div class="col-sm-6"><%= f.input :birth_date, as: :date, start_year: 1900, end_year: Date.today.year, order: [:day, :month, :year], label: 'Data di nascita' %></div>
  </div>
  <div class="form-row">
    <div class="col-sm-6"><%= f.input :address, label: 'Indirizzo' %></div>
    <div class="col-sm-3"><%= f.input :city, as: :select, label: 'Città' %></div>
    <div class="col-sm-3"><%= f.input :province, as: :select, label: 'Provincia' %></div>
  </div>
  <div class="form-row">
    <div class="col-sm-4"><%= f.input :anamnesis, label: 'Anamnesi', input_html: { class: 'tall-input' } %></div>
    <div class="col-sm-4"><%= f.input :eo, label: 'Esame Obiettivo', input_html: { class: 'tall-input' } %></div>
    <div class="col-sm-4"><%= f.input :notes, label: 'Note', input_html: { class: 'tall-input' } %></div>
  </div>

  <% if :after_form %>
    <%= f.input :create_patient_and_exam, as: :hidden, input_html: { value: true } %>
  <% end %>
  <%= f.submit 'Salva', class: 'btn btn-primary' %>
  <% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#patient_province').select2();
    $('#patient_city').select2();
  })
</script>

app/views/patients/_search-result.html.erb
<div class="container mt-3 w-75">
  <div class="row p-2 border shadow">
    <div class="col-sm-5 p-4 align-self-center">
      <h2><%= link_to patient.fullname, patient_path(patient) %></h2>
      <p><%= patient.fiscalcode %></p>
      <p><%= l patient.birth_date, format: :long %> - <%= patient.age %> anni</p>
    </div>
    <div class="col-sm-4 p-4 align-self-center text-center border-left border-right">
      <p>Numero di accessi</p>
      <h1><%= patient.examinations.count %></h1>
    </div>
    <div class="col-sm-3 align-self-center text-center">
      <%= link_to 'Nuovo accesso', new_examination_path(patient_id: patient.id), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/patients/delete.html.erb
<div class="container my-5">
  <h1>Eliminare Record</h1>
  <h5><%= @patient.fullname %></h5>
</div>
<div class="container my-5">
  <p>L'eliminazione del record dal database è un'azione irreversibile.</p>
  <%= link_to 'Elimina Record Paziente', destroy_patient_path(@patient), method: :post, data: { confirm: 'Confermare eliminazione del record '} %>
</div>

app/views/patients/edit.html.erb
<div class="container my-5">
  <h1>Modifica Paziente</h1>
  <h5><%= @patient.fullname %></h5>
</div>
<div class="container">
  <%= simple_form_for @patient do |f| %>
  <div class="form-row">
    <div class="col-sm-6"><%= f.input :fname, label: 'Nome' %></div>
    <div class="col-sm-6"><%= f.input :lname, label: 'Cognome' %></div>
  </div>
  <div class="form-row">
    <div class="col-sm-6"><%= f.input :fiscalcode, label: 'Codice fiscale' %></div>
    <div class="col-sm-6"><%= f.input :birth_date, as: :date, start_year: 1900, end_year: Date.today.year, order: [:day, :month, :year], label: 'Data di nascita' %></div>
  </div>
  <div class="form-row">
    <div class="col-sm-6"><%= f.input :address, label: 'Indirizzo' %></div>
    <div class="col-sm-3"><%= f.input :city, label: 'Città' %></div>
    <div class="col-sm-3"><%= f.input :province, label: 'Provincia' %></div>
  </div>

  <div class="form-row">
    <div class="col-sm-4"><%= f.input :anamnesis, label: 'Anamnesi' %></div>
    <div class="col-sm-4"><%= f.input :eo, label: 'Esame Obiettivo' %></div>
    <div class="col-sm-4"><%= f.input :notes, label: 'Note' %></div>
  </div>

  <%= f.submit 'Salva', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/patients/home.html.erb
<div class="jumbotron mb-5 text-center">
  <h1>ATS Expert</h1>
  <p><%= current_user.fullname %> • <%= current_user.role.capitalize %></p>
</div>
<div class="container my-5">
  <div class="row">

    <div class="col-sm-4">
      <div class="card shadow">
        <div class="card-header">
          <h3>Sede operativa</h3>
        </div>
        <div class="card-body">
          <p class="card-text">Prima di iniziare le attività, ricordarsi di selezionare la propria sede operativa</p>
          <%= link_to 'Cambia sede operativa', user_path(current_user), class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card shadow">
        <div class="card-header">
          <h3>Ricerca paziente</h3>
        </div>
        <div class="card-body">
          <p class="card-text">Cerca un paziente inserendo nome, cognome o entrambi</p>
          <%= link_to 'Ricerca paziente', patients_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

    <div class="col-sm-4">
      <div class="card shadow">
        <div class="card-header">
          <h3>Nuovo Modulo M</h3>
        </div>
        <div class="card-body">
          <p class="card-text">Trova il paziente tramite codice fiscale e compila il modulo M</p>
          <%= link_to 'Nuovo modulo M', search_patients_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/patients/index.html.erb
<div class="container my-5">
  <%= simple_form_for :search, url: patients_path, method: :get do |f| %>
  <div class="form-row w-75 mx-auto">
    <h1>Pazienti</h1>
    <div class="col-11"><%= f.input :query, label: false, placeholder: 'Cerca un paziente per nome o cognome' %></div>
    <div class="col-1"><%= f.submit 'Cerca', class: 'btn btn-primary' %></div>
  </div>
  <% end %>
</div>

<% if !@patients.blank? %>
<div class="container">
  <table class="table table-striped">
    <thead>
      <th class="d-none d-md-block">Id</th>
      <th>Nome</th>
      <th>Cognome</th>
      <th>Codice fiscale</th>
      <th>Città</th>
      <th>Ultimo accesso</th>
      <th width="50">Link</th>
      <th width="70">Modifica</th>
    </thead>
    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td class="d-none d-md-block"><%= patient.id %></td>
          <td><%= patient.fname %></td>
          <td><%= patient.lname %></td>
          <td><%= patient.fiscalcode %></td>
          <td><%= patient.city %></td>
          <td><%= patient.examinations.order(exam_time: :desc).first.present? ? l(patient.examinations.order(exam_time: :desc).first.exam_time, format: :long) : 'nd' %></td>
          <td><%= link_to patient_path(patient) do %><%= fa_icon 'link' %><% end %></td>
          <td><%= link_to edit_patient_path(patient) do %><%= fa_icon 'pencil-alt' %><% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/patients/new.html.erb
<div class="container my-5">
  <h1>Nuovo Paziente</h1>
</div>
<div class="container">
    <%= render 'form' %>
</div>

app/views/patients/new.js.erb
$('#search-results').html('<p>Non sono stati trovati pazienti con questo codice fiscale.<br> Procedere aggiungendo i dati del paziente</p>').append("<%= j render partial: 'form' %>");

app/views/patients/search.html.erb
<div class="container my-5 w-50">
  <h1 class="pb-4">Ricerca paziente</h1>
  <p>Cerca il paziente inserendo il suo nome e cognome</p>
  <%= simple_form_for :search, url: search_patients_path, method: :get, remote: true do |f| %>
    <%= f.input :query, label: false, placeholder: 'Codice fiscale', as: :select %>
    <div class="fluid-container">
      <%= f.submit 'Cerca', class: 'btn btn-primary px-5' %>
      <%= link_to 'Nuovo paziente', new_patient_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

<div class="container my-5 w-75" id="search-results"></div>

<script type="text/javascript">
  $(document).ready(function(){
    $('#search_query').select2({
      ajax: {
        url: "<%= patients_path(format: 'json') %>",
        dataType: "json",
        delay: 250,
        data: function (params) {
          var queryParameters = {
            q: params.term
          }
          return queryParameters;
        },
        processResults: function (data) {
          // Transforms the top-level key of the response object from 'items' to 'results'
          return {
            results: $.map( data, function(patient, i) {
              return { id: patient.fiscalcode, text: patient.name }
            })
          };
        },
      }
        // Additional AJAX parameters go here; see the end of this chapter for the full code of this example
    });
  });
</script>

app/views/patients/search.js.erb
$('#search-results').html("<%= j render partial: 'search-result', locals: { patient: @patients.first, after_form: @after_form } %>");

app/views/patients/show.html.erb
<div class="container mt-5 mb-3">
  <div class="row">
    <div class="col-4 align-self-center">
      <p class="m-0 p-0">Scheda paziente</p>
      <h1><%= @patient.fullname %></h1>
    </div>

    <div class="col-4 align-self-center">

    </div>

    <div class="col-4 align-self-center">
      <% if allowed_to?(:edit?, @patient) %>
        <%= link_to 'Modifica scheda paziente', edit_patient_path(@patient), class: 'btn btn-primary' %>
      <% end %>
      <% if allowed_to?(:new?) %>
        <%= link_to 'Nuovo Esame', new_examination_path(patient_id: @patient), class: 'btn btn-secondary' %>
      <% end %>
    </div>
  </div>
  <hr>
</div>

<div class="container my-3">
  <h3>Dati paziente</h3>
  <div class="row mt-3">
    <div class="col-sm-2 text-center">
      <div class="p-3 border shadow">
        <p class="border-bottom">Sesso</p>
        <h4><%= @patient.gender %></h4>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="p-3 border shadow">
        <p class="border-bottom">Data di nascita</p>
        <h4><%= l @patient.birth_date, format: :long %> | <%= @patient.age %> anni</h4>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="p-3 border shadow">
        <p class="border-bottom">Codice fiscale</p>
        <h4><%= @patient.fiscalcode %></h4>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="p-3 border shadow">
        <p class="border-bottom">Città</p>
        <h4><%= @patient.city %></h4>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <div class="row">
    <div class="col-sm-4">
      <div class="p-3 border">
        <h3>Anamnesi</h3>
        <p class="p-0 m-0"><%= @patient.anamnesis %></p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="p-3 border">
        <h3>Esame Obiettivo</h3>
        <p class="p-0 m-0"><%= @patient.eo %></p>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="p-3 border">
        <h3>Note</h3>
        <p class="p-0 m-0"><%= @patient.notes %></p>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <h3 class="pb-3">Accessi del paziente: <%= @patient.examinations.count %></h3>
  <table class="table table-striped">
    <thead>
      <th width="150">Data</th>
      <th width="400">Situazione</th>
      <th>Esito</th>
      <th width="100">Link</th>
    </thead>
    <tbody>
      <% @patient.examinations.each do |exam| %>
        <tr>
          <td><%= exam.created_at.strftime("%d/%m/%y") %></td>
          <td><%= exam.situation %></td>
          <td><%= exam.result %></td>
          <td><%= link_to examination_path(exam) do %><%= fa_icon 'arrow-right' %><% end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/start.html.erb
<div class="container my-5">
  <div class="card mb-3 shadow">
    <div class="row no-gutters">
      <div class="col-md-5">
        <%= image_tag 'splash.jpg', class: 'card-img' %>
      </div>
      <div class="col-md-7 align-self-center px-5">
        <div class="card-body">
          <h1 class="card-title">ATS Expert</h1>
          <p class="card-text mt-4">Benvenuti su ATS Expert: il software progettato per migliorare la gestione della Continuità Assistenziale<br />Per procedere: eseguite l'accesso o la registrazione sulla piattaforma</p>
          <%= link_to 'Accedi', new_user_session_path, class: 'btn btn-lg btn-primary mt-4 px-5' %>
        </div>
      </div>
    </div>
  </div>
</div>