config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "patients#home"

  resources :patients do
    collection do
      get :home
      get :start
      get :search
    end
    member do
      get :delete
      post :destory
    end
  end

  get 'inizio', to: 'patients#start', as: 'inizio'
  get 'home', to: 'patients#home', as: 'home'

  resources :examinations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :locations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :users do
    member do
      get :delete
      post :destroy
      post :change_location
    end
  end
end

app/models/examination.rb
class Examination < ApplicationRecord
  belongs_to :patient
  belongs_to :user
  belongs_to :location
end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @examinations = Examination.all
    authorize!
  end

  def show
    @examination = Examination.find(params[:id])
    respond_to do |format|
      format.html

      format.pdf do
        pdf = ExaminationPdf.new(@examination)
        send_data pdf.render, filename: 'moduloM.pdf', type: 'application/pdf', disposition: 'inline'
      end

    end
  end

  def new
    if current_user.location.present?
      @patient = Patient.find(params[:patient_id])
      @examination = Examination.new
      authorize! @examination
    else
      flash[:alert] = "Prima di procedere è necessario selezionare una sede operativa"
      redirect_to user_path(current_user)
    end
  end

  def create
    @patient = Patient.find(params[:examination][:patient_id])
    user = User.find(current_user.id)
    location = Location.find(current_user.location.id)
    @examination = Examination.new(examination_params)
    @examination.patient = @patient
    @examination.user = user
    @examination.location = location
    if @examination.save
      flash[:notice] = "Esame salvato"
      redirect_to examination_path(@examination)
    end
  end

  def edit
    @examination = Examination.find(params[:id])
    @patient = @examination.patient
  end

  def update
    @examination = Examination.find(params[:id])
    @examination.update(examination_params)
    flash[:notice] = "Esame aggiornato correttamente"
    redirect_to examination_path(@examination)
  end

  private
  def examination_params
    params.require(:examination).permit(:situation,
                                        :pa_max,
                                        :pa_min,
                                        :bpm,
                                        :breath_freq,
                                        :temperature,
                                        :skin,
                                        :hydration,
                                        :nutrition,
                                        :diuresis,
                                        :alvo,
                                        :nerv_normal,
                                        :nerv_cosc_clouded,
                                        :nerv_cosc_absent,
                                        :nerv_convulsion,
                                        :nerv_romberg,
                                        :nerv_rigor,
                                        :nerv_motor_deficit,
                                        :nerv_sens_deficit,
                                        :pupils_normal_sx,
                                        :pupils_miosis_sx,
                                        :pupils_mydr_sx,
                                        :pupils_fotoreflex_sx,
                                        :pupils_nystagmus_sx,
                                        :pupils_normal_dx,
                                        :pupils_miosis_dx,
                                        :pupils_mydr_dx,
                                        :pupils_fotoreflex_dx,
                                        :pupils_nystagmus_dx,
                                        :lung_normal_sx,
                                        :lung_rumor_sx,
                                        :lung_dry_rumor_sx,
                                        :lung_emphysema_sx,
                                        :lung_normal_dx,
                                        :lung_rumor_dx,
                                        :lung_dry_rumor_dx,
                                        :lung_emphysema_dx,
                                        :heart_normal,
                                        :heart_arhythmia,
                                        :heart_cyanosis,
                                        :heart_edema,
                                        :abdomen_murphy,
                                        :abdomen_blumberg,
                                        :abdomen_rovsing,
                                        :abdomen_ascites,
                                        :abdomen_giordan_sx,
                                        :abdomen_giordan_dx,
                                        :other,
                                        :therapy,
                                        :result,
                                        :urgent,
                                        :patient_id,
                                        :user_id,
                                        :requested_by,
                                        :exam_time,
                                        :exam_location,
                                        :location_id,
                                        :exam_address
                                      )
  end
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
  def boolean(var)
    if var
      fa_icon 'check-circle', class: 'true'
    else
      far_icon 'circle', class: 'false'
    end
  end
end

app/views/examinations/_form.html.erb
<%= simple_form_for @examination do |f| %>
  <div class="container">
    <div class="fluid-container">
      <%= f.input :patient_id, as: :hidden, input_html: { value: @patient.id } %>
    </div>

    <div class="form-row">
      <div class="col-sm-6"><%= f.input :exam_time, as: :datetime, label: 'Data e Ora della visita' %></div>
      <div class="col-sm-6"><%= f.input :exam_location, collection: ['Ambulatoriale', 'Domiciliare'], include_blank: false, label: 'Data e Ora della visita' %></div>
    </div>

    <div class="form-row">
      <div class="col-sm-12"><%= f.input :exam_address, placeholder: 'Indirizzo e città della visita' %></div>
    </div>

    <%= f.input :situation, label: 'Situazione' %>

    <div class="row no-gutters parameters">
      <%= f.input :pa_max, label: 'PA sist' %> /
      <%= f.input :pa_min, label: 'PA diast' %>
      <%= f.input :bpm, label: 'Freq. Card' %>
      <%= f.input :breath_freq, label: 'Freq. Resp' %>
      <%= f.input :temperature, label: 'TC' %>
    </div>
    <hr>
    <div class="row no-gutters">
      <div class="col-2 pr-2">
        <%= f.input :skin, as: :select, collection: ['Normale', 'Pallida', 'Itterica', 'Cianotica'], include_blank: false, label: 'Pelle' %>
      </div>
      <div class="col-2 pr-2">
        <%= f.input :hydration,  include_blank: false, label: 'Idratazione' %>
      </div>
      <div class="col-2 pr-2">
        <%= f.input :nutrition,  include_blank: false, label: 'Stato nutrizionale' %>
      </div>
      <div class="col-2 pr-2">
        <%= f.input :diuresis,  include_blank: false, label: 'Diuresi' %>
      </div>
      <div class="col-2">
        <%= f.input :alvo,  include_blank: false, label: 'Alvo' %>
      </div>
    </div>
    <hr>

    <!-- EO Apparati -->
    <div class="row">
      <!-- Neuro -->
      <div class="col-md-4 mb-3">
        <div class="border p-2">
          <h5>Sistema Nervoso</h5>
          <div class="row">
            <div class="col-10"><p>Normale</p></div>
            <div class="col-2"><%= f.input :nerv_normal, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Coscenza alterata</p></div>
            <div class="col-2"><%= f.input :nerv_cosc_clouded, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Coscenza assente</p></div>
            <div class="col-2"><%= f.input :nerv_cosc_absent, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Convulsioni</p></div>
            <div class="col-2"><%= f.input :nerv_convulsion, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Romberg</p></div>
            <div class="col-2"><%= f.input :nerv_romberg, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Rigor nucalis</p></div>
            <div class="col-2"><%= f.input :nerv_rigor, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Deficit motorio</p></div>
            <div class="col-2"><%= f.input :nerv_motor_deficit, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Deficit motorio</p></div>
            <div class="col-2"><%= f.input :nerv_sens_deficit, as: :boolean, label: false %></div>
          </div>
        </div>
      </div>
      <!-- END Neuro -->

      <!-- Occhi e cardio -->
      <div class="col-md-4 mb-3">
        <div class="border p-2">
          <div class="row">
            <div class="col-8"><h5>Pupille</h5></div>
            <div class="col-2"><p>Dx</p></div>
            <div class="col-2"><p>Sx</p></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Normali</p></div>
            <div class="col-2"><%= f.input :pupils_normal_dx, label: false %></div>
            <div class="col-2"><%= f.input :pupils_normal_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Miosi</p></div>
            <div class="col-2"><%= f.input :pupils_miosis_dx, label: false %></div>
            <div class="col-2"><%= f.input :pupils_miosis_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Midriasi</p></div>
            <div class="col-2"><%= f.input :pupils_mydr_dx, label: false %></div>
            <div class="col-2"><%= f.input :pupils_mydr_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>R. Fotomotori</p></div>
            <div class="col-2"><%= f.input :pupils_fotoreflex_dx, label: false %></div>
            <div class="col-2"><%= f.input :pupils_fotoreflex_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Nistagmo</p></div>
            <div class="col-2"><%= f.input :pupils_nystagmus_dx, label: false %></div>
            <div class="col-2"><%= f.input :pupils_nystagmus_sx, label: false %></div>
          </div>
        </div>
        <div class="border mt-3 p-2">
          <div class="row">
            <div class="col-8"><h5>App Respiratorio</h5></div>
            <div class="col-2"><p>Dx</p></div>
            <div class="col-2"><p>Sx</p></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Indenne</p></div>
            <div class="col-2"><%= f.input :lung_normal_dx, label: false %></div>
            <div class="col-2"><%= f.input :lung_normal_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Rumori</p></div>
            <div class="col-2"><%= f.input :lung_rumor_dx, label: false %></div>
            <div class="col-2"><%= f.input :lung_rumor_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Rumori secchi</p></div>
            <div class="col-2"><%= f.input :lung_dry_rumor_dx, label: false %></div>
            <div class="col-2"><%= f.input :lung_dry_rumor_sx, label: false %></div>
          </div>
          <div class="row">
            <div class="col-8"><p>Rumori secchi</p></div>
            <div class="col-2"><%= f.input :lung_emphysema_dx, label: false %></div>
            <div class="col-2"><%= f.input :lung_emphysema_sx, label: false %></div>
          </div>
        </div>
      </div>
      <!-- END Occhi e cardio -->

      <!-- Cuore e addome -->
      <div class="col-md-4 mb-3">
        <div class="border p-2">
          <h5>App. Cardiocircolatorio</h5>
          <div class="row">
            <div class="col-10"><p>Normale</p></div>
            <div class="col-2"><%= f.input :heart_normal, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Aritmia</p></div>
            <div class="col-2"><%= f.input :heart_arhythmia, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Cianosi</p></div>
            <div class="col-2"><%= f.input :heart_cyanosis, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Edemi</p></div>
            <div class="col-2"><%= f.input :heart_edema, as: :boolean, label: false %></div>
          </div>
        </div>

        <div class="border mt-3 p-2">
          <h5>Addome</h5>
          <div class="row">
            <div class="col-10"><p>Murphy</p></div>
            <div class="col-2"><%= f.input :abdomen_murphy, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Blumberg</p></div>
            <div class="col-2"><%= f.input :abdomen_blumberg, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Rovsing</p></div>
            <div class="col-2"><%= f.input :abdomen_rovsing, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-10"><p>Ascite</p></div>
            <div class="col-2"><%= f.input :abdomen_ascites, as: :boolean, label: false %></div>
          </div>
          <div class="row">
            <div class="col-7"><p>Rumori secchi</p></div>
            <div class="col-2"><%= f.input :abdomen_giordan_dx, label: 'Dx' %></div>
            <div class="col-2"><%= f.input :abdomen_giordan_sx, label: 'Sx' %></div>
          </div>
        </div>
      </div>
      <!-- Cuore e addome -->

    </div>
    <!-- END EO Apparati -->

    <div class="fluid-container my-3">
      <%= f.input :other, label: 'Altro' %>
    </div>

    <div class="fluid-container my-3">
      <%= f.input :therapy, label: 'Terapia e Diagnosi' %>
    </div>

    <div class="fluid-container my-3">
      <div class="row">
        <div class="col-sm-6 align-self-center">
          <%= f.input :result, collection: ['Paziente rinviato o mantenuto al domicilio', 'Disposto ricovero', 'Trasporto con mezzo proprio', 'Inviato in PS tramite 112'] %>
        </div>
        <div class="col-sm-6 align-self-center">
          <%= f.input :urgent, label: "Spuntare se l'intervento non presentava carattere di prestazione non differibile", as: :boolean %>
        </div>
      </div>
    </div>

  </div>


  <%= f.submit 'Salva', class: 'btn btn-primary' %>
</div>
<% end %>

app/views/examinations/edit.html.erb
<div class="container my-5">
  <h1>Modulo M</h1>
  <p><%= @examination.patient.fullname %></p>
</div>
<div class="container my-5">
  <%= render 'form' %>
</div>

app/views/examinations/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-4 align-self-center">
      <h1>Esami</h1>
    </div>
    <div class="col-4 align-self-center">
    </div>
    <div class="col-4 align-self-center">
      <% if allowed_to?(:new?) %>
        <%= link_to 'Nuovo esame', new_examination_path, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

<div class="container my-5">
  <table class="table table-striped">
    <thead>
      <th>Id</th>
      <th>Data</th>
      <th>Paziente</th>
    </thead>
    <tbody>
      <% @examinations.each do |examination| %>
        <tr>
          <td><%= examination.id %></td>
          <td><%= l examination.exam_time, format: :long, locale: :'it' %></td>
          <td><%= examination.patient.fullname %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/examinations/new.html.erb
<div class="container my-5">
  <h1>Modulo M</h1>
</div>
<div class="container my-5">
  <%= render 'form' %>
</div>

app/views/examinations/show.html.erb
<div class="container my-5">
  <div class="row pb-3 border-bottom">
    <div class="col-sm-4 align-self-center">
      <p class="m-0 p-0">Modulo M</p>
      <h1><%= link_to @examination.patient.fullname, patient_path(@examination.patient) %></h1>
      <h4><%= l @examination.exam_time, format: :long %></h4>
    </div>
    <div class="col-sm-4 align-self-center">
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Data di nascita
          <span class="badge badge-primary badge-pill"><%= @examination.patient.birth_date.strftime("%d %B %Y") %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Età:
          <span class="badge badge-primary badge-pill"><%= @examination.patient.age %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Città di residenza
          <span class="badge badge-primary badge-pill"><%= @examination.patient.city %></span>
        </li>
      </ul>
    </div>
    <div class="col-sm-4 align-self-center px-4 text-md-right">
      <p class="m-0">Compilato dal medico</p>
      <h4><%= @examination.user.email %></h4>
      <%= link_to examination_path(@examination, format: 'pdf'), class: 'btn btn-primary', target: '_blank' do %><%= fa_icon 'file-pdf' %><% end %>
    </div>
  </div>
</div>

<% if @examination.exam_address.present? %>
  <div class="container mb-5">
    <h3>Località</h3>
    <p><%= @examination.exam_address %></p>
  </div>
<% end %>

<div class="container bg-light p-4">
  <div class="row">
    <div class="col-sm-8 border-right">
      <div class="pb-3">
        <h3>Situazione</h3>
        <p><%= @examination.situation %></p>
      </div>
      <div class="py-3">
        <h3>Altro</h3>
        <p><%= @examination.other %></p>
      </div>
    </div> <!-- END Col 8 -->

    <div class="col-sm-4 pl-4">
      <div class="pb-3">
        <h3>Terapia e diagnosi</h3>
        <p><%= @examination.therapy %></p>
      </div>
      <div class="py-3">
        <h3>Esito</h3>
        <p><%= @examination.result %></p>
      </div>
    </div> <!-- END Col 4 -->
  </div>
</div>

<div class="container my-4">
  <div class="row justify-content-center">
    <ul class="list-group list-group-horizontal ml-3 mb-3">
      <li class="list-group-item">Pelle: <%= @examination.skin %></li>
      <li class="list-group-item">Idratazione: <%= @examination.hydration %></li>
      <li class="list-group-item">Stato nutrizionale: <%= @examination.nutrition %></li>
      <li class="list-group-item">Diuresi: <%= @examination.diuresis %></li>
      <li class="list-group-item">Alvo: <%= @examination.alvo %></li>
    </ul>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item" data-toggle="tooltip" data-placement="top" title="Pressione Arteriosa">PA: <%= @examination.pa_max %> / <%= @examination.pa_min %></li>
      <li class="list-group-item" data-toggle="tooltip" data-placement="top" title="Frequenza Cardiaca">FC: <%= @examination.bpm %></li>
      <li class="list-group-item" data-toggle="tooltip" data-placement="top" title="Frequenza respiratoria">FR: <%= @examination.breath_freq %></li>
      <li class="list-group-item" data-toggle="tooltip" data-placement="top" title="Temperatura corporea">TC: <%= @examination.temperature %>°</li>
    </ul>
  </div>
</div>

<div class="container my-4">
  <div class="row">
    <!-- sistema nervoso -->
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
          <h3 class="m-0">Sistema nervoso</h3>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Normale
          <span class="badge"><%= boolean(@examination.nerv_normal) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Coscenza obnubilata
          <span class="badge"><%= boolean(@examination.nerv_cosc_clouded) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Coscenza assente
          <span class="badge"><%= boolean(@examination.nerv_cosc_absent) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Convulsioni
          <span class="badge"><%= boolean(@examination.nerv_convulsion) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Romberg
          <span class="badge"><%= boolean(@examination.nerv_romberg) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Rigor Nucalis
          <span class="badge"><%= boolean(@examination.nerv_rigor) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Deficit motorio
          <span class="badge"><%= boolean(@examination.nerv_motor_deficit) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Deficit sensitivo
          <span class="badge"><%= boolean(@examination.nerv_sens_deficit) %></span>
        </li>
      </ul>
    </div>
    <!-- END sistema nervoso -->

    <!-- Occhio -->
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
          <h3 class="m-0">Pupille</h3>
          <span class="badge">Dx</span>
          <span class="badge">Sx</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Normale</p>
          <span class="badge"><%= boolean(@examination.pupils_normal_dx) %></span>
          <span class="badge"><%= boolean(@examination.pupils_normal_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Miosi</p>
          <span class="badge"><%= boolean(@examination.pupils_miosis_dx) %></span>
          <span class="badge"><%= boolean(@examination.pupils_miosis_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Midriasi</p>
          <span class="badge"><%= boolean(@examination.pupils_mydr_dx) %></span>
          <span class="badge"><%= boolean(@examination.pupils_mydr_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>R. Fotom.</p>
          <span class="badge"><%= boolean(@examination.pupils_fotoreflex_dx) %></span>
          <span class="badge"><%= boolean(@examination.pupils_fotoreflex_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Nistagmo</p>
          <span class="badge"><%= boolean(@examination.pupils_nystagmus_dx) %></span>
          <span class="badge"><%= boolean(@examination.pupils_nystagmus_sx) %></span>
        </li>
      </ul>

      <ul class="list-group mt-3">
        <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
          <h3 class="m-0" style="width: 70px">Resp.</h3>
          <span class="badge">Dx</span>
          <span class="badge">Sx</span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Normale</p>
          <span class="badge"><%= boolean(@examination.lung_normal_dx) %></span>
          <span class="badge"><%= boolean(@examination.lung_normal_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Rumori</p>
          <span class="badge"><%= boolean(@examination.lung_rumor_dx) %></span>
          <span class="badge"><%= boolean(@examination.lung_rumor_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Rumori secchi</p>
          <span class="badge"><%= boolean(@examination.lung_dry_rumor_dx) %></span>
          <span class="badge"><%= boolean(@examination.lung_dry_rumor_sx) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Enfisema</p>
          <span class="badge"><%= boolean(@examination.lung_emphysema_dx) %></span>
          <span class="badge"><%= boolean(@examination.lung_emphysema_sx) %></span>
        </li>
      </ul>
    </div>
    <!-- END Occhio e polmone -->

    <!-- Cuore ed addome -->
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
          <h3 class="m-0">App. Cardiocircolatorio</h3>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Normale</p>
          <span class="badge"><%= boolean(@examination.heart_normal) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Aritmia</p>
          <span class="badge"><%= boolean(@examination.heart_arhythmia) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Cianosi</p>
          <span class="badge"><%= boolean(@examination.heart_cyanosis) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Edema</p>
          <span class="badge"><%= boolean(@examination.heart_edema) %></span>
        </li>
      </ul>

      <ul class="list-group mt-3">
        <li class="list-group-item d-flex justify-content-between align-items-center bg-light">
          <h3 class="m-0" style="width: 70px">Addome</h3>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Murphy</p>
          <span class="badge"><%= boolean(@examination.abdomen_murphy) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Blumberg</p>
          <span class="badge"><%= boolean(@examination.abdomen_blumberg) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Rovsing</p>
          <span class="badge"><%= boolean(@examination.abdomen_rovsing) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Ascite</p>
          <span class="badge"><%= boolean(@examination.abdomen_ascites) %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <p>Giordano</p>
          <span class="badge">Dx <%= boolean(@examination.abdomen_giordan_dx) %></span>
          <span class="badge">Sx <%= boolean(@examination.abdomen_giordan_sx) %></span>
        </li>
      </ul>
    </div>
    <!-- END Occhio e cuore -->
  </div>
</div>

<div class="container text-center">
  <% if allowed_to?(:edit?, @examination) %>
    <%= link_to 'Modifica dati modulo M', edit_examination_path(@examination), class: 'btn btn-primary' %>
  <% end %>
</div>