config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "patients#home"

  resources :patients do
    collection do
      get :home
      get :start
      get :search
    end
    member do
      get :delete
      post :destory
    end
  end

  get 'inizio', to: 'patients#start', as: 'inizio'
  get 'home', to: 'patients#home', as: 'home'

  resources :examinations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :locations do
    member do
      get :delete
      post :destroy
    end
  end

  resources :users do
    member do
      get :delete
      post :destroy
      post :change_location
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Medmanager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand:400,500,700&display=swap" rel="stylesheet">
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'ATS Expert', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to user_path(current_user) do %>Sede attuale: <span class="current-location"><%= current_user.location.present? ? current_user.location.title : 'Da impostare' %></span><% end %>
        </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link' %></li>
        <% if user_signed_in? %>
          <% if allowed_to?(:index?) %><li class="nav-item"><%= link_to 'Pazienti', patients_path, class: 'nav-link' %></li><% end %>
        <% end %>
        <li class="nav-item"><%= link_to 'Sedi', locations_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Nuovo Esame', search_patients_path, class: 'nav-link' %></li>

        <% if !user_signed_in? %>
        <li class="nav-item"><%= link_to 'Accedi', new_user_session_path, class: 'nav-link no-anim' %></li>
        <% else %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.fullname %>
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to 'Profilo', user_path(current_user), class: 'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

  <body>
    <% if alert.present? %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if notice.present? %>
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <div class="yield">
      <%= yield %>
    </div>
  </body>

  <footer class="fluid-container py-5">
    <h4>ATS Expert</h4>
    <p>Svilupatto da dott. Diego Di Salvo</p>
  </footer>
</html>